# Generated by Django 4.0 on 2023-05-18 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(10000000000000)]),
        ),
    ]
