# Generated by Django 4.0 on 2023-06-14 01:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_historialform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialform',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historialform',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
