# Generated by Django 4.0 on 2023-06-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_historialform_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialform',
            name='hora',
        ),
        migrations.AlterField(
            model_name='historialform',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
