# Generated by Django 4.0 on 2023-06-14 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_remove_historialform_hora_alter_historialform_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialform',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
