# Generated by Django 4.0 on 2023-06-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_historialform_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.empleado'),
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.libro'),
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.socio'),
        ),
    ]
