# Generated by Django 4.2 on 2023-06-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_historialform_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialForm',
        ),
    ]
