# Generated by Django 4.0 on 2023-06-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_delete_historialform'),
        ('biblioteca', '0008_alter_libro_autor_alter_prestamo_libro_empleado_and_more'),
    ]

    operations = [
    ]
