# Generated by Django 4.0 on 2023-06-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='prestamo_libro',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='prestamo_libro',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo_libro',
            name='socio',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Prestamo_libro',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
