# Generated by Django 4.2 on 2023-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
